baseurl: "https://chrislittleboy.netlify.app/"
languageCode: "en-gb"
title: "Chris Littleboy's blog"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: "chrislittleboy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  footer: "[Twitter](https://twitter.com/chris_littleboy)"

markup:
  goldmark:
    renderer:
      unsafe: true
